# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Maven Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Run Go Rest Smoke
      run: mvn clean test -DsuiteXmlFile=gorest/gorest_testng_smoke.xml
      

    - name: Upload Extent HTML report - Smoke
      continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: go-rest-smoke-report
        path: reports/extent/report_*.html
        
    - name: Run Go Rest Regression
      run: mvn clean test -DsuiteXmlFile=gorest/gorest_testng_regression.xml
      

    - name: Upload Extent HTML report - Regression
      continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: go-rest-regression-report
        path: reports/extent/report_*.html
